### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by francescobonesi** [sturdy-dev/marblezero#3]
When running

```
go install github.com/sturdy-dev/marblezero@latest
```

I get the error

```
# github.com/sturdy-dev/marblezero/achievements
../go/pkg/mod/github.com/sturdy-dev/marblezero@v0.0.0-20221123091024-000002704139/achievements/achievements.go:167:19: undefined: Achievement
```
If this could help:

```
go version go1.19.3 linux/amd64
```

**Comment by jyi2ya** [comment]
https://github.com/sturdy-dev/marblezero/blob/000002704139e6acccb2f93d3ff179cd22b82dba/achievements/achievements.go#L16

I think this `achievement` should be `Achievement`. :)

**Comment by francescobonesi** [comment]
@jyi2ya this works, thank you

**Comment by zegl** [comment]
Thanks, should be fixed now. :-)
